; read char untill a blank is read 

.MODEL SMALL
.STACK 100H
.CODE 

MAIN PROC
  
  MOV AH,1 

REPEAT:   
  INT 21H 
  CMP AL, ' '  ; CHECK BLANK OR NOT
  JNE REPEAT   ; IF NOT BLANK, TAKE INPUT AGAIN 
  JMP EXIT     ; ELSE, JUMP TO EXIT 
  
  EXIT:
    MOV AH, 4CH
    INT 21H   
    
    MAIN ENDP
END MAIN 